spring:
    data:
        rest:
            base-path: /api
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/jreact?useUnicode=true&characterEncoding=utf-8
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    output:
        ansi:
            enabled: DETECT
    thymeleaf:
        mode: LEGACYHTML5

# session 超时30分钟
server:
    servlet:
        session:
            timeout: 600
